import type { Opportunity } from '@ai-cmo/types';
import type { Agent, AgentContext } from '../interface.js';

export class GeoAgent implements Agent {
  readonly name = 'GeoAgent';
  readonly description = 'Identifies geographic market opportunities and regional trends';

  async ingest(_context: AgentContext): Promise<void> {
    // Mock: would fetch from external data sources
  }

  async analyze(_context: AgentContext): Promise<void> {
    // Mock: would process ingested data
  }

  async generateOpportunities(context: AgentContext): Promise<Opportunity[]> {
    return [
      {
        id: crypto.randomUUID(),
        projectId: context.projectId,
        agentRunId: '',
        title: 'Mock opportunity from GeoAgent',
        description: 'This is a placeholder opportunity generated by the GeoAgent stub.',
        category: 'geographic',
        priority: 'medium',
        sourceAgent: this.name,
        sourceUrl: null,
        status: 'new',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];
  }

  async summarize(_context: AgentContext): Promise<string> {
    return 'GeoAgent: Mock analysis complete. Found 1 placeholder opportunity.';
  }
}
